apiVersion: batch/v1
kind: Job
metadata:
  name: playwright-practice
spec:
  parallelism: 2
  completions: 2
  template:
    spec:
      containers:
        - name: test-runner
          image: playwright_allure2/playwright_test:latest
          imagePullPolicy: Always
          command: ["sh", "-c", "mvn clean test"]
          volumeMounts:
            - name: allure-report
              mountPath: /usr/src/app/allure-report
      restartPolicy: Never
      volumes:
        - name: allure-report
          emptyDir: {}
  backoffLimit: 1
